version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - pip install --upgrade pip
            - pip install opencv-python-headless
            - sudo yum install -y dbus-devel dbus-glib-devel
            - pip install -r requirements.txt
            - sudo yum install -y mesa-libGL
    pre_build:
        commands:
            - python --version
artifacts:
    files:
        - '**/*'