version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - pip install --upgrade pip
            - sudo yum install libgl1-mesa-glx
            - export LD_LIBRARY_PATH=/path/to/libGL.so.1:$LD_LIBRARY_PATH
            - pip install -r requirements.txt
    pre_build:
        commands:
            - python --version
artifacts:
    files:
        - '**/*'